---
title: Dalāmības pazīmes
date: "December 15, 2017"
output: pdf_document
---

# Dalāmības pazīmes

**nt-R6.q1** <!--questionType=MC--> Skaitlis dod atlikumu $3$, dalot ar $9$, tad un tikai tad, ja

a. tas ir nepāra un tā pēdējais cipars dalās ar $3$,
b. tā ciparu summa dalās ar $3$,
c. tā ciparu summa dod atlikumu $3$, dalot ar $9$,
d. tā pēdējo divu ciparu veidotais skaitlis dod atlikumu $3$, dalot ar $9$.

**Atbilde:** `c`

**Skaidrojums:** Dots skaitlis $N$ ar decimālpierakstu $\overline{c_nc_{n-1}\ldots{}c_1c_0}$. 
Šajā gadījumā var izteikt skaitli $N$ sekojošā veidā:
$$ N = c_n10^n + c_{n-1}10^{n-1} + \ldots + c_110^1 + c_0. $$
Ja kādu no saskaitāmajiem $c_k10^k$ šajā summā aizstāj ar $c_k$, tad summa samazinās
par $10^kc_k - c_k = (10^k-1)c_k$. Ievērosim, ka skaitlis $10^k-1$ satur decimālpierakstā tikai 
deviņniekus, t.i. šis skaitlis dalās ar $9$.  
Tātad aizstājot $10^kc_k$ ar $c_k$, nemainās atlikums, dalot ar $9$.
Ja aizstājam visus saskaitāmos ar attiecīgajiem cipariem, iegūsim, ka 
skaitļa $N$ ciparu summa $S(N) = c_n+c_{n-1} + \ldots + c_1 + c_0$ dod tādu pašu atlikumu, dalot ar $9$, 
kā pats skaitlis $N$. Tātad pazīme skaitļiem $N$, kuri dod atlikumu $3$, dalot ar $9$, 
ir tā, ka ciparu summa $S(N)$ dod atlikumu $3$, dalot ar $9$.


**nt-R6.q2:** <!--questionType=MC--> Skaitlis dalās ar $6$ tad un tikai tad, ja

a. tas ir pāra skaitlis un tā ciparu summa dalās ar $6$,
b. tas ir pāra skaitlis un tā pēdējais cipars dalās ar $3$,
c. tā pēdējo divu ciparu veidotais skaitlis dalās ar $6$,
d. tā pēdējais cipars dalās ar $2$ un tā ciparu summa dalās ar $3$.

**Atbilde:** `d`

**Skaidrojums:** Lai skaitlis dalītos ar $6$ ir nepieciešami un pietiekami, lai tas 
dalītos ar $2$ un $3$. Tādēļ var kombinēt attiecīgās dalāmības pazīmes: skaitļa pēdējais 
cipars dalās ar $2$ (dalāmības pazīme ar $2$) un ciparu summa dalās ar $3$
(dalāmības pazīme ar $3$). 


**nt-R6.q3:** <!--questionType=MC--> Kurš no dotajiem skaitļiem dalās ar $6$?

a. $1114$,
b. $1124$,
c. $1134$,
d. $1144$. 

**Atbilde:** `c`

**Skaidrojums:** Visi dotie skaitļi dalās ar $2$. Tādēļ jāpārbauda dalāmība ar $3$: 
kuram no skaitļiem ciparu summa dalās ar $3$. Tas izpildās tikai skaitlim 
$1134$, jo $1+1+3+4 = 9$, kas dalās ar $3$. 


**nt-R6.q4:** <!--questionType=MC--> Kurš no dotajiem skaitļiem dalās ar $24$?

a. $232200$,
b. $232324$,
c. $1524$,
d. $2550$".

**Atbilde:** `a`

**Skaidrojums:** Lai skaitlis dalītos ar $24$ ir nepieciešams, lai tas dalītos ar 
$3$ un $8$. Skaitlis $232324$ nedalās ar $3$. Savukārt $1524$ vai $2550$ nedalās ar $8$. 
Atliek vienīgi $232200$.


**nt-R6.q5:** <!--questionType=MC--> Skaitlis dalās ar $12$, ja

a. tas dalās ar $3$ un $4$,
b. tā pēdējo divu ciparu veidotais skaitlis dalās ar $12$,
c. tas ir pāra un dalās ar $6$,
d. tas ir pāra un dalās ar $3$.

**Atbilde:** `a`

**Skaidrojums:** Skaitlis $12$ izsakāms kā divu savstarpēju pirmskaitļu $3$ un $4$ reizinājums. 
Tādēļ ar $12$ dalās tad, ja tas dalās ar $3$ un $4$. 


**nt-R6.q6:** <!--questionType=MC--> Kurš no dotajiem skaitļiem nedalās ar $36$? 

a. $484848484848484848$,
b. $4848484848484848$,
c. $444444444444444444$,
d. $888888888$.

**Atbilde:** `b`

**Skaidrojums:** Ar $36$ dalās tieši tie skaitļi, kas dalās ar $4$ un $9$. Visi uzrakstītie
skaitļi dalās ar $4$. Bet ne visi dalās ar $9$: ja ciparu grupa "48" atkārtojas astoņas 
reizes, tad ciparu summa ir $(4+8)\cdot 8 = 96$, kas dalās ar $3$, bet ne ar $9$. 

**nt-R6.q7:** <!--questionType=MC--> Lai pārbaudītu, vai skaitlis dalās ar $360$, jāpārbauda, vai tas dalās ar

a. $5$, $8$ un $9$,
b. $4$ un $90$,
c. $3$, $5$ un $15$,
d. $12$ un $30$.

**Atbilde:** `a`

**Skaidrojums:** Skaitlis $360$ dalās pirmreizinātājos šādi: $360 = 2^3\cdot 3^2 \cdot 5$. 
Skaitļi $2^3 = 8$, $3^2 = 9$ un $5$ ir savstarpēji pirmskaitļi, tādēļ ar $360$ dalīsies tieši 
tie skaitļi, kas dalās ar $8$, $9$ un $5$. 


**nt-R6.q8:** <!--questionType=MC--> Kurš no dotajiem skaitļiem dalās ar $360$?

a. $1984851280$,
b. $645624560$,
c. $635624660$,
d. $111111111000$.

**Atbilde:** `d`

**Skaidrojums:** Skaitlis, kas beidzas ar "660" nedalās ar $8$ 
(dalāmības pazīme ar $8$ - skaitļa pēdējiem trim cipariem jādalās ar $8$). 
Savukārt skaitļi $1984851280$, $635624660$ nedalās ar $9$, jo ciparu 
summas $1+9+8+4+8+5+1+2+8+0=46$ un $6+4+5+6+2+4+5+6+0=38$ nedalās ar $9$. 


**nt-R6.q9:** <!--questionType=MC--> Kurš no dotajiem skaitļiem dalās ar $11$? 

a. $11851848$,
b. $1086419752$,
c. $1000000000000$,
d. $11111$.

**Atbilde:** `b`

**Skaidrojums:** Skaitlis $1086419752$ apmierina $11$ dalāmības pazīmi - ciparu summas
pāru un nepāru pozīcijās $(1+8+4+9+5) - (0+6+1+7+2) = 27 - 16 = 11$ dalās ar $11$. 
Citi skaitļi neapmierina šo dalāmības pazīmi:  
Skaitlim $11851848$: $(1+8+1+4)-(1+5+8+8)=14-22=8$ nedalās ar $11$.  
Skaitlim $1000000000000$: $(1+0+0+0+0+0+0)-(0+0+0+0+0+0)=1$ nedalās ar $11$.  
Skaitlim $11111$: $(1+1+1)-(1+1) = 1$ nedalās ar $11$. 


**nt-R6.q10:** <!--questionType=MC--> Kurš no dotajiem skaitļiem dalās ar visiem skaitļiem no $1$ līdz $10$?

a. $330$,
b. $720000$,
c. $362880$,
d. $1176$. 

**Atbilde:** `c`

**Skaidrojums:** Skaitlis $362880$ dalās ar $5, 7, 8, 9$. (Dalāmību ar $7$ pārbauda tieši dalot; ar $5$ un $8$ izmantojam 
dalāmības pazīmi par pēdējo ciparu un pēdējiem trim cipariem; ar $9$ izmantojam dalāmības pazīmi par ciparu summu.)  
Starp citu, $362880 = 9! = 1\cdot 2 \cdot 3 \cdot 4 \cdot 5 \cdot 6 \cdot 7 \cdot 8 \cdot 9$  
Citi skaitļi ar kaut ko nedalās:  
$330$ nedalās ar $8$.  
$720000$ nedalās ar $7$.  
$1176$ nedalās ar $9$.


**nt-R6.q11:** <!--questionType=MC--> Kāds cipars jāievieto $\ast$ vietā 
skaitlī $235\!\ast{}\!870$, lai tas dalītos ar $90$?

a. $9$,
b. $3$,
c. $2$,
d. $0$,
e. $11$. 

**Atbilde:** `c`

**Skaidrojums:** Skaitlis beidzas ar $0$, tātad, acīmredzot, dalās ar $2 \cdot 5 = 10$. Tam jādalās arī 
ar $9$, t.i. $2 + 3 + 5 + \ast + 8+7+0 = 10 + \ast + 15 = 25 + \ast$ jādalās ar $9$. 
Tātad $\ast$ vietā var ievietot $2$ vai $11$, bet tikai $2$ ir cipars. 


**nt-part1-04.q12:** <!--questionType=INPUT|length=4--> Sareizināja visus naturālos skaitļus, 
kas mazāki par $100$. Kādi ir pēdējie četri cipari reizinājumā: 
$$1 \cdot 2 \cdot 3 \cdot \ldots \cdot 97 \cdot 98 \cdot 99.$$

**Atbilde:** `0000`

**Daļējs kredīts:** Ierakstīts mazāks skaits nuļļu nekā "0000". 

**Skaidrojums:** Starp skaitļiem no $1$ līdz $99$ būs pietiekami daudzi skaitļi, kas dalās ar $10$. 
Tos sareizinot iegūsim skaitli, kas dalās ar $10^4 = 10000$. Tātad reizinājums beidzas ar četrām nullēm. 


**nt-part1-04.q13:** <!--questionType=INPUT|length=1--> Sareizināja visus nepāru divciparu skaitļus, 
kas mazāki par $30$. Kāds ir pēdējais cipars reizinājumā 
$$11 \cdot 13 \cdot \ldots \cdot 27 \cdot 29.$$

**Atbilde:** `5`

**Skaidrojums:** Starp nepāru skaitļiem atradīsies tie, kas dalās ar $5$, tādēļ arī reizinājums dalīsies
ar $5$ (turklāt ir nepāru skaitlis kā nepāru skaitļu reizinājums). Tātad reizinājums beidzas ar ciparu $5$
(nevis ar $0$). 








